package com.Project.GoodToTrade.Enums;

public enum SubCategory {
    MOBILE, LAPTOP, SOFA, TABLE, SHIRT, PANTS, NOVEL, TEXTBOOK, POWER_TOOLS, HAND_TOOLS, SOFT_TOYS, COMPUTERS, EDUCATIONAL_TOYS,
    HEALTH, CAMPING, POKEMON, WATER, FIRE, NORMAL, BUG, ELECTRIC
}
